language: java
deploy:
  provider: heroku
  api_key:
    secure: RDKozp/szA/vC9aw8GZ1DHss6uRSVRpFmYNGwwiZ5UsWialKwuEuudhNAUfQyDD/iVsH5yw6FAqbWpeiXvJ+SOv1/D+MUSOoWnoqfyp4awDPGszP8pteRl5UXFeCodHUspT8Q5a7KsO3P8is0Xw+J2rVCQEu0Qd6Ndx0UgPCjK7OxN7wCopmN2gucR7lDfInq+DekZ19UEHQBbSFNeiy+Rk+/szRVaZOvvvbJhp/p2dnxe+TSuEITpGWG3XTZEq+Oj7plD7vg/jMy4onJk8oG7meWRyE4Y2AMLW9Ly+JiZfrAES8+tPf7RFFCQgzcHuhwac/R+eM6liXJl5tAPXtGjOMee39eZWg4m/AR5AmnnjTjenghScbWJgzV8wRmEpuOLUKkYS/KZ9q4XrjAVFPFAZvxmFrs6DmAxnvf9HecMUPDovpMZzNsIwpwWrt1YvgjuBKF7T8gCtJrl1CraHsPtQMUiLk1A6GBhdEbr4y7QRzH6yUKTLfoNQdGQGUX+4QUpJeDaUXAuJuE8EsAcZhFCmPIEKv/8uK4wYYYTFtKUMY2Bf1Cv0jprBfpDF5KOKhQBQHOeVmDrckOyPxADBpkuX1LBcF4WHe5yjLIb7oE1SeUsbICiEz6mkZAg0r3e4WErblSrw+UQ1ZyuzSMRO81/9OJO12DUL5D+XShgE0MYU=
  app: lightrip-server
